export const routes = {
    root: "/",
    noAuthRoutes: {
        signIn: "/signin",
        signUp: "/signup",
        emailVerification: "/email-verification",
        signInVerification: "/signin-verification",
        forgotPassword: "/forgot-password",
        resetPassVerification: "/reset-password-verification",
        newPassword: "/new-password",
        passwordResetSuccess: "/password-reset-success",
    },
    authRoutes: {
        planSelection: "/plan-selection",
        planPurchase: "/plan-purchase",
        planPurchaseSuccess: "/plan-purchase-success",
        advisorSelection: "/advisor-selection",
        accountTypeSelection: "/account-type-selection",
        kycProcess: "/kyc-process",
        kycDisclosures: "/kyc-disclosures",
        kycThankYou: "/kyc-thankyou",
        accountOverview: "/account-overview",
        dashboard: "/dashboard",
        customerDashboard: "/customer-dashboard",
        stockSearch: "/stock-search",
        stockResults: "/shares-etf-search-results",
        productDetails: "/product-details",
        personalInformation: "/personal-information",
        investmentProfile: "/investment-profile",
        watchlists: "/watchlists",
        myLists: "/my-watchlist",
        advisorDashboard: "/advisor-dashboard",
        rmDashboard: "/relationship-manager-dashboard",
        listRM: "/list-rm",
        viewRM: "/view-rm",
        editRM: "/edit-rm",
        addRM: "/add-rm",
        invest: "/invest",
        selectFundsRegister: "/select-funds-register",
        selectFundsThankYou: "/select-funds-thankyou",
        transactionHistory: "/transaction-history",
        clientList: "/clients-list",
        recommendedPortfolios: "/recommended_portfolios",
        advisorProfile: "/advisor-profile",
        overseasBankAccount: "/overseas-bank-account",
        advisorKyc: "/advisor-kyc-process",
        advisorKycDisclosures: "/advisor-kyc-disclosures",
        advisorKycDisclosureLink: "/advisor-kyc-disclosures-link",
        orderHistory: "/order-history",
        rmProfile: "/rm-profile",
        orderConfirmation: "/order-confirmation",
        clientDisclosure: "/client-disclosure",
        clientDetails: "/client-account-details",
        clientKyc: "/client-kyc-process",
        portfolioOverview:'/portfolio-overview',
        advisorHome: "/advisor-home",
        addMoney: "/add-money",
        withdrawMoney: "/withdraw-money",
        rmNewPassword:"/rm-change-password",
        addBank:"/add-bank",
        bankDetails:"/bank-details"
    },
};

